# syntax = docker/dockerfile:1

#! BASE ####################################################
FROM node:slim as base

## Setting up the work directory
WORKDIR /app

# Update ENVIRONMENT variable $PATH
ENV PATH /app/node_modules/.bin:$PATH

## Exposing server port
EXPOSE 3000

## create a non-root user for security 
## Optional because user `node` exist in this image
### RUN useradd -m -s /bin/bash username

#! DEVTOOLS ################################################
FROM base as devtools

## Install devtools
RUN apt update && apt-get -y --no-install-recommends install nano zsh curl tmux fontconfig git ca-certificates \
    build-essential # Add build essentials for compiling code

## Add admin user
RUN useradd admin && \
    echo "admin:admin" | chpasswd && \
    apt-get update && \
    apt-get -y --no-install-recommends install sudo && \
    echo "admin ALL=(ALL) ALL" >> /etc/sudoers

## User settings

### Set default ZSH
RUN chsh -s /bin/zsh node

### select User
USER node

### Install tmux plugins and theme
RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && \
    touch ~/.tmux.conf && \
    echo 'set -g default-terminal "screen-256color"' >> ~/.tmux.conf && \
    echo '#Toggle status bar by Prefix+I (default ctrl+b+I)' >> ~/.tmux.conf && \
    echo 'bind b run-shell "tmux setw -g status \$(tmux show -g -w status | grep -q off && echo on || echo off)"' >> ~/.tmux.conf && \
    echo 'set -g mouse on' >> ~/.tmux.conf && \
    echo 'set -g @plugin "tmux-plugins/tpm"' >> ~/.tmux.conf && \
    echo 'set -g @plugin "tmux-plugins/tmux-resurrect"' >> ~/.tmux.conf && \
    echo 'set -g @plugin "jimeh/tmux-themepack"' >> ~/.tmux.conf && \
    echo 'set -g @themepack "powerline/default/gray"' >> ~/.tmux.conf && \
    echo 'run-shell "~/.tmux/plugins/tpm/tpm"' >> ~/.tmux.conf

### Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
    ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
    ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting && \
    git clone https://github.com/zsh-users/zsh-autosuggestions \
    ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --all

RUN sed -i -e 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc && \
    sed -i -e 's/plugins=(git)/plugins=(git zsh-syntax-highlighting zsh-autosuggestions fzf tmux)/' ~/.zshrc && \
    echo 'export PATH="$PATH:/home/rails/.local/bin"' >> ~/.zshrc

## Solve nerd font font issue
USER root
RUN apt-get install -y --no-install-recommends locales && \
    locale-gen en_US.UTF-8 && \
    sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    TERM=xterm-256color

## Install additional tools
RUN apt-get -y --no-install-recommends install \
    vim \
    less \
    htop \
    wget \
    tree

### Clear cache
RUN rm -rf /var/lib/apt/lists/*

USER node
CMD ["/bin/zsh"]





#? DEVELOPMENT ############################################
FROM devtools as development

## Declaring env
ENV NODE_ENV development

## Copy package file
USER root
COPY package.json package-lock.json ./
RUN chmod ugo+rwx package-lock.json
RUN chown -R node:node ./
USER node

## Installing dependencies
RUN npm install

## Copy application code
## Copy application code
COPY . .

## Starting our application
## CMD [ "nodemon", "index.js" ]
## CMD [ "node", "index.js" ]

